### ISSUE TITLE
Footnotes appear to be broken

### ISSUE THREAD

**Issue by 0xCLARITY** [alanorth/hugo-theme-bootstrap4-blog#34] opened 2017-01-03 22:56 UTC
Clicking on the "return" footnote reference for a footnote does not redirect to the part of the post where the footnote is referenced but instead back to the index page. 

I was using a custom `<!--more-->` tag when the behavior was observed.

**Comment by alanorth** [comment] 2017-01-04 10:28
Thanks for the report. I'm not using footnotes myself, so I haven't experienced this. Can you give me some content Markdown so I can reproduce this and try to fix it?

**Comment by alanorth** [comment] 2017-01-05 12:22
You're right, footnotes are broken. I tested with the popular [hyde](http://themes.gohugo.io/hyde/) theme and they are working properly. Let me look into it.

**Comment by alanorth** [comment] 2017-01-05 13:30
I figured it out: there was an unnecessary `<base>` tag in the site metadata. The behavior of this tag is specifically to set a [base for relative links](https://developer.mozilla.org/en/docs/Web/HTML/Element/base). This is also the cause for the issue identified in #22.

Fixed in https://github.com/alanorth/hugo-theme-bootstrap4-blog/commit/fa0df752a1207b80c78fb02813e3cbb9bc20ea1d.

**Closed as completed by alanorth** 2017-01-05 13:30 UTC
